version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: 'development'
    labels:
      - dependencies
      - dependabot
      - web-team
    ignore:
      - dependency-name: 'eslint'
        versions: ['9.x']
      - dependency-name: 'mongoose'
        versions: ['8.x']
      - dependency-name: 'express'
        versions: ['5']
      - dependency-name: 'jest'
        versions: ['30']
      - dependency-name: '@types/jest'
        versions: ['30']
      - dependency-name: 'jest-extended'
        versions: ['6']
      - dependency-name: 'dotenv'
        versions: ['17']
