version: '3.7'
services:
  mongodb:
    image: mongo:3.6
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - bnet

networks:
  bnet:
    driver: bridge
